discord_token = "YOUR_TOKEN_HERE"
client_id = "YOUR_CLIENT_ID"
prefix = "YOUR_PREFIX_HERE"
bot_folder = "./YOUR_STORAGE_FOLDER_HERE/"
cfg_path = bot_folder + "botdata.cfg"
dbg_path = bot_folder + "debug.log"
